version: '3'

services:
  
  nodeserver:
    build:
      context: ./nodeserver
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-patrik-fullcycle-network
    volumes:
      - ./nodeserver:/usr/src/app
    command: >
      bash -c "npm i && node index.js" 
    depends_on: 
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - node-patrik-fullcycle-network
    tty: true
    ports: 
      - "8080:80"
    depends_on: 
      - nodeserver

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - node-patrik-fullcycle-network

networks:
  node-patrik-fullcycle-network:
    driver: bridge